name: Save Location Data

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: 'UUID'
        required: true
      location-data:
        description: 'Location Data'
        required: true

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create new website
        run: |
          cp -R template $dir_name
          cd $dir_name
          echo '${{ github.event.inputs.location-data }}' > locations.json
        env:
          dir_name: ${{ github.event.inputs.uuid }}

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Add location data for ${{ github.event.inputs.uuid }}"
          for EXPONENTIAL_BACKOFF in {1..10}; do
            git push && break;
            DELAY=$((2**$EXPONENTIAL_BACKOFF))
            sleep $DELAY
            echo "Push failed. Rebasing"
            git pull --rebase
          done
